version: "3"

services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
